### ISSUE TITLE
ALLERT TROJAN

### ISSUE THREAD

**Issue by TheFedelino01** [daemondevin/GitHubDesktopPortable#8]
This project contains a trojan!
Don't trust it!! If you do a virus scan, it will be immediatly found!
Check this: https://www.virustotal.com/gui/file/7a236d9eb5b5cf55f52fe026d891ea4722b460b50b7557c750a2f64e76b9e33a/detection

**Comment by daemondevin** [comment]
You do realize that GitHub is an OPEN SOURCE place, right? That means any fucking project you find here you may review that source code it took to create it. 

Now run along my retarded little friend; go read the code yourself... fucking moron.

**Comment by TheFedelino01** [comment]
I exactly know that gitHub is a open source Place but this does not justify the fact that you spread freely any trojans you want.
So moderate your language and be honest with people.

**Comment by daemondevin** [comment]
You really don't know the teen false positive, huh?

Wow.

**Comment by TheFedelino01** [comment]
You don’t know the term “information”.
I said to pay attention because doing a virus-scan, it will be detected as a trojan.
You had better try to understand why it is detected instead of insulting me. :~

**Comment by daemondevin** [comment]
Cry about it, build a bridge and get the fuck on over it. If I could care less, I probably would. Go nuke yourself another Hot Pocket and find someone else to bother because shit isn't for you. Oh yeah, don't forget your glass of Code Red Mountain Dew. 

Fucking square.

**Comment by TheFedelino01** [comment]
When I speak with dickheads this is the result.
 
Grow.
